"""
Summary of LangChain Concepts Learned So Far
============================================

Based on our movie information extraction project (CineSage), here are the core LangChain concepts we have learned and applied:

1. Environment Management:
   - Using `dotenv` (load_dotenv, find_dotenv) to securely load API keys (e.g., MISTRAL_API_KEY) from a .env file.

2. LLM Initialization:
   - Importing and instantiating a model via LangChain's integration packages.
   - Example: Using `ChatMistralAI` from `langchain_mistralai` and specifying a model version (e.g., "mistral-small-2506").

3. Prompt Templates:
   - Using `ChatPromptTemplate` from `langchain_core.prompts` to structure interactions with the LLM.
   - Defining multi-part prompts with specific roles like "system" (for instructions and guidelines) and "human" (for the actual user input).
   - Using placeholders (like `{paragraph}`) in the prompt string to dynamically insert user data.

4. Invocation & Chaining:
   - Formatting the prompt by calling `.invoke()` on the template and passing a dictionary with the expected variables (e.g., `prompt.invoke({"paragraph": para})`).
   - Calling the model by passing the formatted prompt using `.invoke()` (e.g., `model.invoke(final_prompt)`).

5. Response Handling:
   - Accessing the text generated by the model through the `.content` attribute of the response object.
"""
